// screens/styles/onboardingStyles.js
import { StyleSheet } from 'react-native';

export const onboardingStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    paddingHorizontal: 24,
    paddingVertical: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroContainer: {
    width: '100%',
    height: 280,
    borderRadius: 24,
    backgroundColor: '#e0f2fe',
    marginBottom: 40,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  layer1: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#bfdbfe',
    borderRadius: 20,
    transform: [{ rotate: '12deg' }],
    opacity: 0.6,
  },
  layer2: {
    ...StyleSheet.absoluteFillObject,
    top: 8,
    left: 8,
    right: 8,
    bottom: 8,
    backgroundColor: '#93c5fd',
    borderRadius: 20,
    transform: [{ rotate: '-6deg' }],
    opacity: 0.8,
  },
  centerBox: {
    width: 64,
    height: 64,
    backgroundColor: 'white',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  icon: {
    fontSize: 28,
    color: '#2563eb',
  },
  measureTopLeft: {
    position: 'absolute',
    top: 16,
    left: 16,
    backgroundColor: 'white',
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 12,
    elevation: 2,
  },
  measureBottomRight: {
    position: 'absolute',
    bottom: 32,
    right: 16,
    backgroundColor: 'white',
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 12,
    elevation: 2,
  },
  measureText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#4b5563',
  },
  content: {
    width: '100%',
    maxWidth: 360,
    alignItems: 'center',
    gap: 12,
  },
  appName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 4,
  },
  divider: {
    width: 48,
    height: 4,
    backgroundColor: '#2563eb',
    borderRadius: 999,
    marginBottom: 12,
  },
  headline: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#111827',
    marginBottom: 8,
  },
  subtext: {
    fontSize: 16,
    textAlign: 'center',
    color: '#6b7280',
    marginBottom: 24,
  },
  button: {
    width: '100%',
    backgroundColor: '#2563eb',
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
    marginBottom: 12,
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 16,
  },
  learnMore: {
    color: '#6b7280',
    fontSize: 14,
    fontWeight: '500',
  },
});